// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: xuser.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XUserGroup int32

const (
	XUserGroup_NULL     XUserGroup = 0
	XUserGroup_STRANGER XUserGroup = 1
	XUserGroup_NOR      XUserGroup = 2
	XUserGroup_ADMIN    XUserGroup = 3
)

// Enum value maps for XUserGroup.
var (
	XUserGroup_name = map[int32]string{
		0: "NULL",
		1: "STRANGER",
		2: "NOR",
		3: "ADMIN",
	}
	XUserGroup_value = map[string]int32{
		"NULL":     0,
		"STRANGER": 1,
		"NOR":      2,
		"ADMIN":    3,
	}
)

func (x XUserGroup) Enum() *XUserGroup {
	p := new(XUserGroup)
	*p = x
	return p
}

func (x XUserGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XUserGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_xuser_proto_enumTypes[0].Descriptor()
}

func (XUserGroup) Type() protoreflect.EnumType {
	return &file_xuser_proto_enumTypes[0]
}

func (x XUserGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use XUserGroup.Descriptor instead.
func (XUserGroup) EnumDescriptor() ([]byte, []int) {
	return file_xuser_proto_rawDescGZIP(), []int{0}
}

type CaptchaProduct int32

const (
	CaptchaProduct_UNKNOW    CaptchaProduct = 0
	CaptchaProduct_ANJI_PLUS CaptchaProduct = 1
	CaptchaProduct_ALI       CaptchaProduct = 2
	CaptchaProduct_TENCENT   CaptchaProduct = 3
)

// Enum value maps for CaptchaProduct.
var (
	CaptchaProduct_name = map[int32]string{
		0: "UNKNOW",
		1: "ANJI_PLUS",
		2: "ALI",
		3: "TENCENT",
	}
	CaptchaProduct_value = map[string]int32{
		"UNKNOW":    0,
		"ANJI_PLUS": 1,
		"ALI":       2,
		"TENCENT":   3,
	}
)

func (x CaptchaProduct) Enum() *CaptchaProduct {
	p := new(CaptchaProduct)
	*p = x
	return p
}

func (x CaptchaProduct) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaptchaProduct) Descriptor() protoreflect.EnumDescriptor {
	return file_xuser_proto_enumTypes[1].Descriptor()
}

func (CaptchaProduct) Type() protoreflect.EnumType {
	return &file_xuser_proto_enumTypes[1]
}

func (x CaptchaProduct) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaptchaProduct.Descriptor instead.
func (CaptchaProduct) EnumDescriptor() ([]byte, []int) {
	return file_xuser_proto_rawDescGZIP(), []int{1}
}

// 用户登录方式类型
type XUserLoginCode int32

const (
	XUserLoginCode_NUL XUserLoginCode = 0
	// 手机+验证码
	XUserLoginCode_MOBILE_AUTH_CODE XUserLoginCode = 1
	// 邮箱+密码
	XUserLoginCode_EMAIL_PASSWORD XUserLoginCode = 2
	// 手机+密码
	XUserLoginCode_MOBILE_PASSWORD XUserLoginCode = 3
)

// Enum value maps for XUserLoginCode.
var (
	XUserLoginCode_name = map[int32]string{
		0: "NUL",
		1: "MOBILE_AUTH_CODE",
		2: "EMAIL_PASSWORD",
		3: "MOBILE_PASSWORD",
	}
	XUserLoginCode_value = map[string]int32{
		"NUL":              0,
		"MOBILE_AUTH_CODE": 1,
		"EMAIL_PASSWORD":   2,
		"MOBILE_PASSWORD":  3,
	}
)

func (x XUserLoginCode) Enum() *XUserLoginCode {
	p := new(XUserLoginCode)
	*p = x
	return p
}

func (x XUserLoginCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XUserLoginCode) Descriptor() protoreflect.EnumDescriptor {
	return file_xuser_proto_enumTypes[2].Descriptor()
}

func (XUserLoginCode) Type() protoreflect.EnumType {
	return &file_xuser_proto_enumTypes[2]
}

func (x XUserLoginCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use XUserLoginCode.Descriptor instead.
func (XUserLoginCode) EnumDescriptor() ([]byte, []int) {
	return file_xuser_proto_rawDescGZIP(), []int{2}
}

type XNebulaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 组合appID sign
	ReqID string `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Data  string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// 毫秒UTC
	Utc   uint64 `protobuf:"varint,4,opt,name=utc,proto3" json:"utc,omitempty"`
	Sign  string `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	AppID uint32 `protobuf:"varint,6,opt,name=appID,proto3" json:"appID,omitempty"`
}

func (x *XNebulaReq) Reset() {
	*x = XNebulaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XNebulaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XNebulaReq) ProtoMessage() {}

func (x *XNebulaReq) ProtoReflect() protoreflect.Message {
	mi := &file_xuser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XNebulaReq.ProtoReflect.Descriptor instead.
func (*XNebulaReq) Descriptor() ([]byte, []int) {
	return file_xuser_proto_rawDescGZIP(), []int{0}
}

func (x *XNebulaReq) GetReqID() string {
	if x != nil {
		return x.ReqID
	}
	return ""
}

func (x *XNebulaReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *XNebulaReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *XNebulaReq) GetUtc() uint64 {
	if x != nil {
		return x.Utc
	}
	return 0
}

func (x *XNebulaReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *XNebulaReq) GetAppID() uint32 {
	if x != nil {
		return x.AppID
	}
	return 0
}

type XNebulaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Utc     uint64 `protobuf:"varint,4,opt,name=utc,proto3" json:"utc,omitempty"`
	Sign    string `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *XNebulaResp) Reset() {
	*x = XNebulaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XNebulaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XNebulaResp) ProtoMessage() {}

func (x *XNebulaResp) ProtoReflect() protoreflect.Message {
	mi := &file_xuser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XNebulaResp.ProtoReflect.Descriptor instead.
func (*XNebulaResp) Descriptor() ([]byte, []int) {
	return file_xuser_proto_rawDescGZIP(), []int{1}
}

func (x *XNebulaResp) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *XNebulaResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *XNebulaResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *XNebulaResp) GetUtc() uint64 {
	if x != nil {
		return x.Utc
	}
	return 0
}

func (x *XNebulaResp) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

// 发送短信验证码
type SendAuthMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 业务动作ID
	ActionID int32  `protobuf:"varint,1,opt,name=actionID,proto3" json:"actionID,omitempty"`
	Mobile   string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 行为验证 产品商
	CaptchaProduct int32 `protobuf:"varint,3,opt,name=captchaProduct,proto3" json:"captchaProduct,omitempty"`
	// 行为验证
	CaptchaData string `protobuf:"bytes,4,opt,name=captchaData,proto3" json:"captchaData,omitempty"`
}

func (x *SendAuthMsgReq) Reset() {
	*x = SendAuthMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAuthMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAuthMsgReq) ProtoMessage() {}

func (x *SendAuthMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_xuser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAuthMsgReq.ProtoReflect.Descriptor instead.
func (*SendAuthMsgReq) Descriptor() ([]byte, []int) {
	return file_xuser_proto_rawDescGZIP(), []int{2}
}

func (x *SendAuthMsgReq) GetActionID() int32 {
	if x != nil {
		return x.ActionID
	}
	return 0
}

func (x *SendAuthMsgReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SendAuthMsgReq) GetCaptchaProduct() int32 {
	if x != nil {
		return x.CaptchaProduct
	}
	return 0
}

func (x *SendAuthMsgReq) GetCaptchaData() string {
	if x != nil {
		return x.CaptchaData
	}
	return ""
}

// 用户注册
type XUserSignupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 手机号
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 短信验证码
	AuthMsgCode string `protobuf:"bytes,3,opt,name=authMsgCode,proto3" json:"authMsgCode,omitempty"`
	// 手机号
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// 邮箱验证码
	EmailAuthCode string `protobuf:"bytes,5,opt,name=emailAuthCode,proto3" json:"emailAuthCode,omitempty"`
}

func (x *XUserSignupReq) Reset() {
	*x = XUserSignupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuser_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XUserSignupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XUserSignupReq) ProtoMessage() {}

func (x *XUserSignupReq) ProtoReflect() protoreflect.Message {
	mi := &file_xuser_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XUserSignupReq.ProtoReflect.Descriptor instead.
func (*XUserSignupReq) Descriptor() ([]byte, []int) {
	return file_xuser_proto_rawDescGZIP(), []int{3}
}

func (x *XUserSignupReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *XUserSignupReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *XUserSignupReq) GetAuthMsgCode() string {
	if x != nil {
		return x.AuthMsgCode
	}
	return ""
}

func (x *XUserSignupReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *XUserSignupReq) GetEmailAuthCode() string {
	if x != nil {
		return x.EmailAuthCode
	}
	return ""
}

// 登录
type XUserLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 登录类别 XUserLoginCode，手机+验证码登录、邮箱+密码登录、手机+密码登录
	LoginCode   uint32 `protobuf:"varint,1,opt,name=loginCode,proto3" json:"loginCode,omitempty"`
	Mobile      string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password    string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	AuthMsgCode string `protobuf:"bytes,5,opt,name=authMsgCode,proto3" json:"authMsgCode,omitempty"`
	// 所属组(XUserGroup)，区分访客、普通用户、管理员等类型
	GroupCode uint32 `protobuf:"varint,6,opt,name=groupCode,proto3" json:"groupCode,omitempty"`
	// 行为验证 产品商
	CaptchaProduct int32 `protobuf:"varint,10,opt,name=captchaProduct,proto3" json:"captchaProduct,omitempty"`
	// 行为验证
	CaptchaData string `protobuf:"bytes,11,opt,name=captchaData,proto3" json:"captchaData,omitempty"`
}

func (x *XUserLoginReq) Reset() {
	*x = XUserLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuser_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XUserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XUserLoginReq) ProtoMessage() {}

func (x *XUserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_xuser_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XUserLoginReq.ProtoReflect.Descriptor instead.
func (*XUserLoginReq) Descriptor() ([]byte, []int) {
	return file_xuser_proto_rawDescGZIP(), []int{4}
}

func (x *XUserLoginReq) GetLoginCode() uint32 {
	if x != nil {
		return x.LoginCode
	}
	return 0
}

func (x *XUserLoginReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *XUserLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *XUserLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *XUserLoginReq) GetAuthMsgCode() string {
	if x != nil {
		return x.AuthMsgCode
	}
	return ""
}

func (x *XUserLoginReq) GetGroupCode() uint32 {
	if x != nil {
		return x.GroupCode
	}
	return 0
}

func (x *XUserLoginReq) GetCaptchaProduct() int32 {
	if x != nil {
		return x.CaptchaProduct
	}
	return 0
}

func (x *XUserLoginReq) GetCaptchaData() string {
	if x != nil {
		return x.CaptchaData
	}
	return ""
}

// 登录结果
type XUserLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint32 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token  string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *XUserLoginResp) Reset() {
	*x = XUserLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuser_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XUserLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XUserLoginResp) ProtoMessage() {}

func (x *XUserLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_xuser_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XUserLoginResp.ProtoReflect.Descriptor instead.
func (*XUserLoginResp) Descriptor() ([]byte, []int) {
	return file_xuser_proto_rawDescGZIP(), []int{5}
}

func (x *XUserLoginResp) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *XUserLoginResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *XUserLoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_xuser_proto protoreflect.FileDescriptor

var file_xuser_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x78, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x78,
	0x75, 0x73, 0x65, 0x72, 0x22, 0x88, 0x01, 0x0a, 0x0a, 0x58, 0x4e, 0x65, 0x62, 0x75, 0x6c, 0x61,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x74, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x75, 0x74, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x22,
	0x79, 0x0a, 0x0b, 0x58, 0x4e, 0x65, 0x62, 0x75, 0x6c, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x74, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x75, 0x74, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x53,
	0x65, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x61, 0x70, 0x74, 0x63,
	0x68, 0x61, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x70,
	0x74, 0x63, 0x68, 0x61, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x44, 0x61, 0x74, 0x61, 0x22, 0xa2, 0x01, 0x0a, 0x0e,
	0x58, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x73, 0x67,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x64, 0x65,
	0x22, 0x81, 0x02, 0x0a, 0x0d, 0x58, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75,
	0x74, 0x68, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61,
	0x70, 0x74, 0x63, 0x68, 0x61, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x0e, 0x58, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0x38, 0x0a, 0x0a, 0x58, 0x55, 0x73, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x52, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x4e, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e,
	0x10, 0x03, 0x2a, 0x41, 0x0a, 0x0e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4e, 0x4a, 0x49, 0x5f, 0x50, 0x4c, 0x55, 0x53, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x4c, 0x49, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x45, 0x4e, 0x43,
	0x45, 0x4e, 0x54, 0x10, 0x03, 0x2a, 0x58, 0x0a, 0x0e, 0x58, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x55, 0x4c, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f,
	0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x4f,
	0x42, 0x49, 0x4c, 0x45, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x03, 0x42,
	0x50, 0x0a, 0x26, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x78, 0x66,
	0x6f, 0x72, 0x74, 0x2e, 0x58, 0x4e, 0x65, 0x62, 0x75, 0x6c, 0x61, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x66, 0x6f, 0x72, 0x74, 0x2f, 0x58, 0x4e, 0x65, 0x62,
	0x75, 0x6c, 0x61, 0x55, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xuser_proto_rawDescOnce sync.Once
	file_xuser_proto_rawDescData = file_xuser_proto_rawDesc
)

func file_xuser_proto_rawDescGZIP() []byte {
	file_xuser_proto_rawDescOnce.Do(func() {
		file_xuser_proto_rawDescData = protoimpl.X.CompressGZIP(file_xuser_proto_rawDescData)
	})
	return file_xuser_proto_rawDescData
}

var file_xuser_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_xuser_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_xuser_proto_goTypes = []interface{}{
	(XUserGroup)(0),        // 0: xuser.XUserGroup
	(CaptchaProduct)(0),    // 1: xuser.CaptchaProduct
	(XUserLoginCode)(0),    // 2: xuser.XUserLoginCode
	(*XNebulaReq)(nil),     // 3: xuser.XNebulaReq
	(*XNebulaResp)(nil),    // 4: xuser.XNebulaResp
	(*SendAuthMsgReq)(nil), // 5: xuser.SendAuthMsgReq
	(*XUserSignupReq)(nil), // 6: xuser.XUserSignupReq
	(*XUserLoginReq)(nil),  // 7: xuser.XUserLoginReq
	(*XUserLoginResp)(nil), // 8: xuser.XUserLoginResp
}
var file_xuser_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xuser_proto_init() }
func file_xuser_proto_init() {
	if File_xuser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xuser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XNebulaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xuser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XNebulaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xuser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAuthMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xuser_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XUserSignupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xuser_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XUserLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xuser_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XUserLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xuser_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xuser_proto_goTypes,
		DependencyIndexes: file_xuser_proto_depIdxs,
		EnumInfos:         file_xuser_proto_enumTypes,
		MessageInfos:      file_xuser_proto_msgTypes,
	}.Build()
	File_xuser_proto = out.File
	file_xuser_proto_rawDesc = nil
	file_xuser_proto_goTypes = nil
	file_xuser_proto_depIdxs = nil
}
